/*
 * This source file was generated by the Gradle 'init' task
 */
package sudoku.test

class SudokuTests extends munit.FunSuite:
  test("hello"):
    val obtained = 42
    val expected = 42
    assertEquals(obtained, expected)